### ISSUE TITLE
UnhandledPromiseRejectionWarning in @babel plugin

### ISSUE THREAD

**Issue by MacroMan** [nhn/toast-ui.doc#14]
## Describe the bug

Running `tuidoc` outputs the following error:
```
(node:15979) UnhandledPromiseRejectionWarning: SyntaxError: This experimental syntax requires enabling the parser plugin: 'nullishCoalescingOperator' (29:114)
    at _class.raise (/home/david/personal-projects/oth3d/node_modules/documentation/node_modules/@babel/parser/lib/index.js:3939:15)
    at _class.expectPlugin (/home/david/personal-projects/oth3d/node_modules/documentation/node_modules/@babel/parser/lib/index.js:5253:18)
    at _class.parseExprOp (/home/david/personal-projects/oth3d/node_modules/documentation/node_modules/@babel/parser/lib/index.js:5843:16)
    at _class.parseExprOps (/home/david/personal-projects/oth3d/node_modules/documentation/node_modules/@babel/parser/lib/index.js:5822:17)
    at _class.parseMaybeConditional (/home/david/personal-projects/oth3d/node_modules/documentation/node_modules/@babel/parser/lib/index.js:5784:21)
    at _class.parseMaybeAssign (/home/david/personal-projects/oth3d/node_modules/documentation/node_modules/@babel/parser/lib/index.js:5731:21)
    at _class.parseMaybeAssign (/home/david/personal-projects/oth3d/node_modules/documentation/node_modules/@babel/parser/lib/index.js:2585:53)
    at _class.parseObjectProperty (/home/david/personal-projects/oth3d/node_modules/documentation/node_modules/@babel/parser/lib/index.js:6798:101)
    at _class.parseObjPropValue (/home/david/personal-projects/oth3d/node_modules/documentation/node_modules/@babel/parser/lib/index.js:6823:99)
    at _class.parseObjPropValue (/home/david/personal-projects/oth3d/node_modules/documentation/node_modules/@babel/parser/lib/index.js:2370:47)
(node:15979) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:15979) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

My `tuidoc.config.json` file:
```
{
    "header": {
        "logo": false,
        "title": {
            "text": "Open TH 3d",
            "linkUrl": "https://github.com/MacroMan/oth3d"
        },
        "version": false
    },
    "footer": [
        {
            "title": "David Wakelin",
            "linkUrl": "https://davidwakelin.co.uk/"
        }
    ],
    "main": {
        "filePath": "README.md"
    },
    "api": {
        "filePath": "src/js",
        "permalink": false
    },
    "pathPrefix": "oth3d.doc"
}
```

## To Reproduce

Run `tuidoc` with the above config.

## Desktop (please complete the following information):

- OS: - Ubuntu 20.04
- Browser: Node CLI
- Version: v12.22.5

## Additional context

Is this a problem with my config?

**Comment by adhrinae** [comment]
@MacroMan 
Can you try it on Node.js v10? It only works on v10 at the moment.
